"""Schedule automated job searches via cron/systemd timers."""

import subprocess
import sys
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from jobsentry.config import get_settings

app = typer.Typer(no_args_is_help=True)
console = Console()

# Wrapper script that activates venv and runs a pipeline
SCRIPT_TEMPLATE = """#!/bin/bash
# JobSentry automated job search — generated by 'jobsentry schedule setup'
set -e

VENV="{venv_path}"
source "$VENV/bin/activate"

LOG_DIR="{log_dir}"
mkdir -p "$LOG_DIR"
LOG="$LOG_DIR/jobsentry_$(date +%Y%m%d_%H%M%S).log"

echo "=== JobSentry run $(date) ===" >> "$LOG"

# Search all boards
{search_commands}

# Fetch full descriptions for new jobs
jobsentry jobs fetch >> "$LOG" 2>&1

# AI match new jobs
{match_command}

# Send email digest of top matches (with resume)
jobsentry notify digest >> "$LOG" 2>&1 || true

# Send Telegram summary
jobsentry notify summary >> "$LOG" 2>&1 || true

echo "=== Done $(date) ===" >> "$LOG"

# Keep only last 30 logs
ls -t "$LOG_DIR"/jobsentry_*.log 2>/dev/null | tail -n +31 | xargs -r rm
"""

CRON_COMMENT = "# JobSentry automated job search"


def _find_venv() -> Path:
    """Find the active virtualenv."""
    venv = Path(sys.prefix)
    if (venv / "bin" / "activate").exists():
        return venv
    # Fallback to project .venv
    project_venv = Path.cwd() / ".venv"
    if (project_venv / "bin" / "activate").exists():
        return project_venv
    return venv


def _get_script_path() -> Path:
    settings = get_settings()
    return settings.data_dir / "run_search.sh"


@app.command()
def setup(
    boards: str = typer.Option(
        "clearancejobs,linkedin",
        "--boards",
        "-b",
        help="Comma-separated list of boards to search",
    ),
    hour: int = typer.Option(8, "--hour", help="Hour to run (0-23)"),
    minute: int = typer.Option(0, "--minute", help="Minute to run (0-59)"),
    frequency: str = typer.Option(
        "every-5-days",
        "--frequency",
        "-f",
        help="How often: daily, weekdays, twice-daily, every-5-days",
    ),
    dry_run: bool = typer.Option(
        False, "--dry-run", help="Show what would be configured without installing"
    ),
):
    """Set up automated job searches via cron."""
    settings = get_settings()
    settings.ensure_dirs()
    venv_path = _find_venv()
    log_dir = settings.data_dir / "logs"

    # Build search commands
    board_list = [b.strip() for b in boards.split(",")]
    search_lines = []
    for board in board_list:
        search_lines.append(f'jobsentry jobs search --board {board} >> "$LOG" 2>&1 || true')
    search_commands = "\n".join(search_lines)

    # Match command (only if API key is set)
    match_command = ""
    if settings.anthropic_api_key:
        match_command = 'jobsentry jobs match >> "$LOG" 2>&1 || true'
    else:
        match_command = 'echo "Skipping match — JOBSENTRY_ANTHROPIC_API_KEY not set" >> "$LOG"'

    # Write the script
    script_path = _get_script_path()
    script_content = SCRIPT_TEMPLATE.format(
        venv_path=venv_path,
        log_dir=log_dir,
        search_commands=search_commands,
        match_command=match_command,
    )
    script_path.write_text(script_content)
    script_path.chmod(0o755)

    # Build cron schedule
    if frequency == "daily":
        cron_schedule = f"{minute} {hour} * * *"
    elif frequency == "weekdays":
        cron_schedule = f"{minute} {hour} * * 1-5"
    elif frequency == "twice-daily":
        hour2 = (hour + 12) % 24
        cron_schedule = f"{minute} {hour},{hour2} * * *"
    elif frequency == "every-5-days":
        cron_schedule = f"{minute} {hour} */5 * *"
    else:
        console.print(
            f"[red]Unknown frequency '{frequency}'. Use: daily, weekdays, twice-daily, every-5-days[/red]"
        )
        raise typer.Exit(1)

    cron_line = f"{cron_schedule} {script_path}"

    if dry_run:
        console.print(
            Panel("[bold yellow]Dry Run — nothing will be installed[/bold yellow]", style="yellow")
        )
        console.print(f"  Schedule:  {cron_schedule} ({frequency})")
        console.print(f"  Boards:    {', '.join(board_list)}")
        console.print(f"  Script:    {script_path}")
        console.print(f"  Logs:      {log_dir}/")
        console.print(f"\n  Cron line: {cron_line}")
        console.print("\n[dim]Remove --dry-run to install.[/dim]")
        return

    # Install to crontab
    try:
        result = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
        existing = result.stdout if result.returncode == 0 else ""

        # Remove old entries
        lines = [
            line
            for line in existing.splitlines()
            if CRON_COMMENT not in line and "jobsentry" not in line and "airecruiter" not in line
        ]
        lines.append(CRON_COMMENT)
        lines.append(cron_line)
        lines.append("")  # trailing newline

        new_crontab = "\n".join(lines)
        subprocess.run(["crontab", "-"], input=new_crontab, text=True, check=True)

        console.print(Panel("[bold green]Schedule set up successfully[/bold green]", style="green"))
        console.print(f"  Script: {script_path}")
        console.print(f"  Schedule: {cron_schedule} ({frequency})")
        console.print(f"  Boards: {', '.join(board_list)}")
        console.print(f"  Logs: {log_dir}/")
        console.print()
        console.print("[dim]View with 'crontab -l'. Remove with 'jobsentry schedule remove'.[/dim]")

    except FileNotFoundError:
        console.print("[yellow]crontab not found. You can run the script manually:[/yellow]")
        console.print(f"  {script_path}")


@app.command()
def remove():
    """Remove the automated search schedule."""
    try:
        result = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
        if result.returncode != 0:
            console.print("[yellow]No crontab found.[/yellow]")
            return

        lines = [
            line
            for line in result.stdout.splitlines()
            if CRON_COMMENT not in line and "jobsentry" not in line and "airecruiter" not in line
        ]

        new_crontab = "\n".join(lines) + "\n" if lines else ""
        subprocess.run(["crontab", "-"], input=new_crontab, text=True, check=True)

        # Remove the script
        script_path = _get_script_path()
        if script_path.exists():
            script_path.unlink()

        console.print("[green]Schedule removed.[/green]")

    except FileNotFoundError:
        console.print("[yellow]crontab not available on this system.[/yellow]")


@app.command()
def status():
    """Show current schedule and recent run logs."""
    settings = get_settings()
    log_dir = settings.data_dir / "logs"
    script_path = _get_script_path()

    # Check crontab
    try:
        result = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
        crontab = result.stdout if result.returncode == 0 else ""
        cron_lines = [
            line for line in crontab.splitlines() if "jobsentry" in line or "airecruiter" in line
        ]
    except FileNotFoundError:
        cron_lines = []

    if cron_lines:
        console.print(Panel("[bold green]Schedule Active[/bold green]", style="green"))
        for line in cron_lines:
            console.print(f"  {line}")
    else:
        console.print(Panel("[yellow]No schedule configured[/yellow]", style="yellow"))
        console.print("[dim]Run 'jobsentry schedule setup' to configure.[/dim]")

    console.print(
        f"\n  Script: {'exists' if script_path.exists() else 'not found'} ({script_path})"
    )

    # Show recent logs
    if log_dir.exists():
        logs = sorted(log_dir.glob("jobsentry_*.log"), reverse=True)[:5]
        # Also check legacy log names
        if not logs:
            logs = sorted(log_dir.glob("airecruiter_*.log"), reverse=True)[:5]
        if logs:
            console.print()
            table = Table(title="Recent Runs")
            table.add_column("Log File", max_width=45)
            table.add_column("Size", width=10)
            for log in logs:
                size = log.stat().st_size
                size_str = f"{size:,} B" if size < 1024 else f"{size / 1024:.1f} KB"
                table.add_row(log.name, size_str)
            console.print(table)
            console.print(f"\n[dim]View latest: cat {logs[0]}[/dim]")
    else:
        console.print("\n  [dim]No logs yet.[/dim]")
